Repository May-I-AI-Integrated-Platform/FE, pull requests merged in 2025-03, with the labels that each got.

#2 [FEAT] #1 home div 틀 구성
  package-lock.json
  package.json
  src/App.jsx
  src/Home.jsx
  src/components/home/Chat.jsx
  src/components/home/Header.jsx
  src/components/home/Inputbar.jsx
  src/components/home/Sidebar.jsx
  src/css/common.css
  src/css/home/home.css
  src/css/home/sidebar.css
  yarn.lock
Labels: :sparkles: feature

#5 [FEAT] #4 헤더바 구현
  src/components/home/Header.jsx
  src/css/home/header.css
Labels: :sparkles: feature

#7 [FEAT] #3 사이드 바 구현
  image/newChatIcon.png
  image/settingIcon.png
  image/sidebarIcon.png
  src/App.jsx
  src/Home.jsx
  src/components/home/Sidebar.jsx
  src/components/home/sidebar/ChatHistory.jsx
  src/components/home/sidebar/SettingIcon.jsx
  src/components/home/sidebar/TopIcon.jsx
  src/css/home/sidebar.css
Labels: :sparkles: feature

#10 [FIX] #8 사이드바 레이아웃 수정
  src/Home.jsx
  src/components/home/Header.jsx
  src/components/home/sidebar/ChatHistory.jsx
  src/css/home/header.css
  src/css/home/home.css
  src/css/home/sidebar.css
Labels: :bug: bugfix

#12 [FEAT] #11 설정창 표시 기능 구현
  src/Home.jsx
  src/components/home/Sidebar.jsx
  src/components/home/TokenSetting.jsx
  src/components/home/sidebar/SettingIcon.jsx
  src/css/home/home.css
  src/css/home/tokenSetting.css
Labels: :sparkles: feature

#15 [FEAT] #13 프로필 모달 구현
  image/cancelIcon.png
  src/Home.jsx
  src/components/home/Header.jsx
  src/css/home/header.css
Labels: :sparkles: feature

#17 Fix/16/chat area
  src/components/home/ChatArea.jsx
  src/css/home/chatArea.css
  src/css/home/inputbar.css
Labels: :bug: bugfix, :sparkles: feature
